
clear
clc

app_name = 'SpikerBot';
main_app_file = 'C:\Users\Christopher Harris\NeuroRobot\NeuroRobotToolbox\neurorobot.m';
additional_files = 'C:\Users\Christopher Harris\NeuroRobot\NeuroRobotToolbox';

compiler_opts = compiler.build.StandaloneApplicationOptions(main_app_file, ...
    'AdditionalFiles', additional_files, ...
    'ExecutableName', app_name, ...
    'Verbose', 'on', ...
    'ExecutableIcon', 'C:\Users\Christopher Harris\NeuroRobot\Gallery\robot.jpg', ...
    'ExecutableSplashScreen', 'C:\Users\Christopher Harris\NeuroRobot\Gallery\robot.jpg', ...
    'OutputDir', 'C:\Users\Christopher Harris\NeuroRobot\SpikerBot_Build', ...
    'SupportPackages', {'IP Cameras', 'Deep Learning Toolbox Model for GoogLeNet Network'});
compiler_results = compiler.build.standaloneApplication(compiler_opts);

package_opts = compiler.package.InstallerOptions(...
    'ApplicationName', app_name, ...
    'AuthorCompany', 'Backyard Brains', ...
    'AuthorName', 'Christopher Harris', ...
    'InstallerName', strcat(app_name, '_Installer'), ...
    'InstallerSplash', 'C:\Users\Christopher Harris\NeuroRobot\Gallery\robot.jpg', ...
    'InstallerIcon', 'C:\Users\Christopher Harris\NeuroRobot\Gallery\robot.jpg', ...
    'InstallerLogo', 'C:\Users\Christopher Harris\NeuroRobot\Gallery\strip.jpg', ...
    'OutputDir', 'C:\Users\Christopher Harris\NeuroRobot\SpikerBot_Installer', ...
    'Summary','The SpikerBot app is a brain simulator for educational neurorobotics. For information, visit https://github.com/BackyardBrains/NeuroRobot', ...
    'Description', 'You are about to download and install the SpikerBot app and required parts of the Matlab Runtime Library. An internet connection IS required.', ...
    'Version', '1.5', ...
    'RuntimeDelivery', 'web');

compiler.package.installer(compiler_results, 'options', package_opts);
