
clear
clc

app_name = 'SpikerBot';
main_app_file = 'C:\Users\Christopher Harris\NeuroRobot\NeuroRobotToolbox\neurorobot.m';
additional_files = 'C:\Users\Christopher Harris\NeuroRobot\NeuroRobotToolbox';

compiler_opts = compiler.build.StandaloneApplicationOptions(main_app_file, ...
    'AdditionalFiles', additional_files, ...
    'ExecutableName', app_name, ...
    'Verbose', 'on', ...
    'ExecutableIcon', 'C:\Users\Christopher Harris\NeuroRobot\Gallery\robot.jpg', ...
    'ExecutableSplashScreen', 'C:\Users\Christopher Harris\NeuroRobot\Gallery\robot.jpg', ...
    'OutputDir', 'C:\Users\Christopher Harris\NeuroRobot\SpikerBot_build', ...
    'SupportPackages', {'IP Cameras', 'Deep Learning Toolbox Model for GoogLeNet Network'});
compiler_results = compiler.build.standaloneApplication(compiler_opts);

package_opts = compiler.package.InstallerOptions(...
    'ApplicationName', app_name, ...
    'AuthorCompany', 'Backyard Brains', ...
    'AuthorName', 'Christopher Harris', ...
    'InstallerName', strcat(app_name, '_win_installer'), ...
    'InstallerSplash', 'C:\Users\Christopher Harris\NeuroRobot\Gallery\robot.jpg', ...
    'InstallerIcon', 'C:\Users\Christopher Harris\NeuroRobot\Gallery\robot.jpg', ...
    'InstallerLogo', 'C:\Users\Christopher Harris\NeuroRobot\Gallery\strip.jpg', ...
    'OutputDir', 'C:\Users\Christopher Harris\NeuroRobot\SpikerBot_installer', ...
    'Summary','The SpikerBot App is a brain simulator for educational neurorobotics. Design brains and interface with robots.', ...
    'Description', 'You are about to download and install the SpikerBot app and the Matlab Runtime Library. Internet connection required.', ...
    'Version', '1.1', ...
    'RuntimeDelivery', 'web');

compiler.package.installer(compiler_results, 'options', package_opts);
