name: neurorobot
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'
dependencies:
  async: 2.11.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mic_stream: 
    path: ./PLUGINS/mic_stream
  flutter_audio_waveforms: 
    path: ./PLUGINS/flutter_audio_waveforms1.1.1.3/
  # winaudio: 
  #   path: ./PLUGINS/winaudio
  # window_manager: 0.3.6
  # nativec: 
  #   path: ./PLUGINS/nativec/
  # auto_orientation: 2.3.1

  another_xlider: 3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
