name: neurorobot
description: A cool neurorobot 
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.1+65

environment:
  sdk: '>=2.19.3 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  # google_fonts: 6.2.1
  google_fonts: 4.0.4
  tflite_flutter: 0.10.4
  image: 4.0.17

  # http: ^1.1.0
  async: 2.11.0
  cupertino_icons: ^1.0.2
  # mic_stream: 
  #   path: ./PLUGINS/mic_stream
  flutter_audio_waveforms: 
    path: "./PLUGINS/flutter_audio_waveforms1.1.1.3/"
  intl: 0.18.1
  another_xlider: 3.0.1
  matrix_gesture_detector_pro: 1.0.0

  # connectivity_plus: 5.0.2
  # network_info_plus: 4.1.0+1
  # web_socket_channel: 2.4.0
  web_socket_channel: 2.4.4
  # websocket_universal: 1.2.4
  
  # socket_io_client: 2.0.3+1
  flutter_mjpeg: 2.0.4
  path_provider: 2.1.1
  # path: 1.8.3
  path: 1.9.0
  package_info_plus: 8.0.0
  # opencv_ffi:
  #   path: ./PLUGINS/opencv_ffi/
    
  infinite_canvas:  
    path: ./PLUGINS/infinite_canvas-0.0.9/
  flutter_svg: 2.0.7
  shared_preferences: 2.2.1
  responsive_grid: 2.4.4
  easy_animated_tabbar: 0.0.1
  metooltip: 0.0.7
  fialogs: 2.1.0
  screenshot: 2.1.0
  sn_progress_dialog: 1.1.3
  mutex: 3.1.0

  # WEB CHANGE
  ffi: 2.1.0  
  native_opencv:
    path: ./PLUGINS/native_opencv


  # opencv_ffi: 1.1.0
  # fps_widget: 1.0.1+2
  # tflite_flutter: 0.10.2
  #native
  # winaudio:
  #   path: ./PLUGINS/winaudio
  # nativec:
  #   path: "./PLUGINS/nativec/"
  window_manager: 0.3.6
  auto_orientation: 2.3.1
  gesture_x_detector: 1.1.1
  animated_battery_gauge: 0.2.0
  # super_drag_and_drop: 0.8.17
  # cart_stepper: ^4.1.2

  firebase_core: 2.17.0
  firebase_analytics: 10.5.1
  firebase_crashlytics: 3.3.7
  firebase_performance: 0.9.2+7

  # firebase_core: 2.24.2
  # firebase_analytics: 10.7.4
  # firebase_performance: 0.9.3+8
  # firebase_crashlytics: 3.4.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  fonts:
    - family: BybHanddrawn
      fonts:
      - asset: assets/fonts/BYBHandDrawn.otf
  assets:
    - assets/icons/
    - assets/bg/
    - assets/models/
  uses-material-design: true
