
close all
clear

load('.\gTruths\gTruth1.mat')

[imds,blds] = objectDetectorTrainingData(gTruth, 'WriteLocation', horzcat('.\g', num2str(ntruth)));

options = trainingOptions(...
    'sgdm', ...
    'MiniBatchSize', 64, ...
    'LearnRateSchedule','piecewise', ...
    'LearnRateDropFactor',0.2, ...
    'LearnRateDropPeriod',5, ...
    'MaxEpochs', 5, ...
    'executionenvironment', 'gpu');

net = alexnet;

rcnn = trainRCNNObjectDetector(t, net, options);
