
clear
clc

% mcc -o SpikerBot -W 'main:SpikerBot,version=1.0' -T link:exe ...
%     -d 'C:\Users\Christopher Harris\NeuroRobot\SpikerBot\for_testing' ...
%     -R '-logfile,SpikerBot_compile_log' -v 'C:\Users\Christopher Harris\NeuroRobot\NeuroRobotToolbox\neurorobot.m' ...
%     -a 'C:\Users\Christopher Harris\NeuroRobot\NeuroRobotToolbox' ...
%     -r 'C:\Users\Christopher Harris\NeuroRobot\SpikerBot_resources\icon.ico' ...
%     -Z 'IP Cameras'

app_name = 'SpikerBot';
main_app_file = 'C:\Users\Christopher Harris\NeuroRobot\NeuroRobotToolbox\neurorobot.m';
additional_files = 'C:\Users\Christopher Harris\NeuroRobot\NeuroRobotToolbox';
output_dir = strcat('C:\Users\Christopher Harris\NeuroRobot\', app_name, '\for_testing');

compiler_results = compiler.build.standaloneApplication(main_app_file, ...
    'AdditionalFiles', additional_files, 'ExecutableName', app_name, 'Verbose', 'on', ...
    'OutputDir', output_dir, 'SupportPackages', {'IP Cameras'});

output_dir = strcat('C:\Users\Christopher Harris\NeuroRobot\', app_name, '\for_distribution');

compiler.package.installer(compiler_results, 'ApplicationName', app_name, ...
    'AuthorCompany','Backyard Brains', 'AuthorName','Christopher Harris', ...
    'InstallerName', strcat(app_name, '_Installer'), 'Summary','Brain simulator for educational neurorobotics', ...
    'Version', '1.0', 'RuntimeDelivery','web', 'OutputDir', output_dir, 'AuthorEmail', 'christopher@backyardbrains.com');
