
clear
clc

% mcc -o SpikerBot -W 'main:SpikerBot,version=1.0' -T link:exe ...
%     -d 'C:\Users\Christopher Harris\NeuroRobot\SpikerBot\for_testing' ...
%     -R '-logfile,SpikerBot_compile_log' -v 'C:\Users\Christopher Harris\NeuroRobot\NeuroRobotToolbox\neurorobot.m' ...
%     -a 'C:\Users\Christopher Harris\NeuroRobot\NeuroRobotToolbox' ...
%     -r 'C:\Users\Christopher Harris\NeuroRobot\SpikerBot_resources\icon.ico' ...
%     -Z 'IP Cameras'

mcc -o SpikerBot -W 'main:SpikerBot,version=1.0' -T link:exe ...
    -d 'C:\Users\Christopher Harris\NeuroRobot\SpikerBot_wizard\for_testing' ...
    -R '-logfile,SpikerBot_wizard_log' -v 'C:\Users\Christopher Harris\NeuroRobot\NeuroRobotToolbox\neurorobot.m' ...
    -a 'C:\Users\Christopher Harris\NeuroRobot\NeuroRobotToolbox' ...
    -r 'C:\Program Files\MATLAB\R2022a\toolbox\compiler\packagingResources\default_icon.ico' ...
    -Z 'IP Cameras' -Z 'OS Generic Video Interface' -Z 'Deep Learning Toolbox Model for GoogLeNet Network' 

mcc -o SpikerBot -W 'main:SpikerBot,version=1.0' -T link:exe -d ...
    'C:\Users\Christopher Harris\NeuroRobot\SpikerBot_wizard\for_testing' ...
    -R '-logfile,SpikerBot_wizard_log' -v 'C:\Users\Christopher Harris\NeuroRobot\NeuroRobotToolbox\neurorobot.m' ...
    -a 'C:\Users\Christopher Harris\NeuroRobot\NeuroRobotToolbox' ...
    -r 'C:\Program Files\MATLAB\R2022a\toolbox\compiler\packagingResources\default_icon.ico' ...
    -Z none 

app_name = 'SpikerBot';
main_app_file = 'C:\Users\Christopher Harris\NeuroRobot\NeuroRobotToolbox\neurorobot.m';
additional_files = 'C:\Users\Christopher Harris\NeuroRobot\NeuroRobotToolbox';

% compiler_opts = compiler.build.StandaloneApplicationOptions(main_app_file, ...
%     'AdditionalFiles', additional_files, ...
%     'ExecutableName', app_name, ...
%     'Verbose', 'on', ...
%     'OutputDir', 'C:\Users\Christopher Harris\NeuroRobot\standalone_build', ...
%     'SupportPackages', {'IP Cameras'});

compiler_opts = compiler.build.StandaloneApplicationOptions(main_app_file);

compiler_results = compiler.build.standaloneApplication(main_app_file, compiler_opts);

package_opts = compiler.package.InstallerOptions(...
    'ApplicationName', app_name, ...
    'AuthorCompany', 'Backyard Brains', ...
    'AuthorName', 'Christopher Harris', ...
    'InstallerName', strcat(app_name, '_package_installer'), ...
    'OutputDir', 'C:\Users\Christopher Harris\NeuroRobot\package_installer', ...
    'Summary','The SpikerBot app is a brain simulator for educational neurorobotics.', ...
    'Description', 'This installer contains the SpikerBot app and the required Matlab Runtime Library.', ...
    'Version', '1.0', ...
    'RuntimeDelivery', 'web');

compiler.package.installer(compiler_results, package_opts);
